# This file was generated by GoReleaser. DO NOT EDIT.
class Kopia < Formula
  desc "Fast and secure open source backup."
  homepage "https://kopia.io"
  version "0.7.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kopia/kopia/releases/download/v0.7.0-rc1/kopia-0.7.0-rc1-macOS-x64.tar.gz"
    sha256 "4ada6f075300d7f7b210ccf38c57078ccd1de082ab6cb88899ee74c31dedfd9a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kopia/kopia/releases/download/v0.7.0-rc1/kopia-0.7.0-rc1-linux-x64.tar.gz"
      sha256 "f0222df5438e8224c43b15aafa4c28563774314cb0fa2e8c37b99317bf5d010a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kopia/kopia/releases/download/v0.7.0-rc1/kopia-0.7.0-rc1-linux-arm64.tar.gz"
        sha256 "4a843f2c8f22bbd2472872415656c450839b57802f7a72ae1541d0fe5dbc3ce0"
      else
        url "https://github.com/kopia/kopia/releases/download/v0.7.0-rc1/kopia-0.7.0-rc1-linux-arm.tar.gz"
        sha256 "ebfb72105cdfc6a0bedd93d7f3c4513539c8603bfe794ca58357f67229d52e13"
      end
    end
  end

  def install
    bin.install "kopia"
  end
end
